version: '3.9'

services:
  #new service (java_app)
  java_app:
    container_name: java_app
    image: odhnz/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/db_carpark
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - java_db

  #old service (postgres)
  java_db:
    container_name: java_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_carpark
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}